import {currentDate,projectSchedule} from './engine.js?v=10';
import {careerProfile,agentChoices,pendingAuditions,pendingOffers,preparation,prepareAudition,attendCallback,hireAgent,searchAgentOffers,negotiateOffer,franchisePlan,offerConflict,acceptCareerOffer,declineCareerOffer,terminateContract,resolveProductionEvent} from './career.js?v=10';

export function careerHubMarkup(s,catalogue,data,{esc,money,fmtDate,history=false}){
 const profile=careerProfile(s),projects=new Map([...catalogue,...s.projects].map(p=>[p.id,p])),date=currentDate(s);
 const callbacks=pendingAuditions(s),offers=pendingOffers(s),contracts=s.contracts.filter(c=>c.personId===s.activeId&&(history||c.status==='active')).slice(-10);
 const events=s.productionEvents.filter(e=>e.personId===s.activeId&&e.status==='open');
 return `<div class="card"><div class="eyebrow">Acting career</div><h2>Your representation</h2><p>Professional reputation <strong>${profile.reputation}/100</strong> · ${profile.agent?`${esc(profile.agent.name)} · ${Math.round(profile.agent.commission*100)}% commission`:'Self-represented'}</p><p class="muted">Agents improve access and fees. Signed contracts reserve filming dates; unsigned offers can be compared freely.</p><details><summary>Choose representation</summary>${agentChoices(s).map(a=>`<p><strong>${esc(a.name)}</strong> · ${Math.round(a.commission*100)}%<br><span class="muted">${esc(a.description)}${a.level===2?' Requires reputation 40 and fame or industry respect 15.':a.level===3?' Requires reputation 50, fame 40 and industry respect 25.':' Requires reputation 25.'}</span><br><button class="outline" data-hire-agent="${a.level}" ${!a.eligible||profile.agent?.level===a.level?'disabled':''}>${profile.agent?.level===a.level?'Your agent':'Choose this agent'}</button></p>`).join('')}${profile.agent?'<button class="outline" data-hire-agent="0">Represent yourself</button>':''}</details>${profile.agent?'<button class="secondary" data-agent-search>Ask agent to find roles</button>':''}</div>
 ${events.map(e=>`<div class="card"><div class="eyebrow">A fictional on-set dilemma</div><h2>${esc(e.title)}</h2><p>${esc(e.body)}</p><button class="secondary" data-set-event="${esc(e.id)}" data-response="cooperate">Agree to the extra demands</button><button class="outline" data-set-event="${esc(e.id)}" data-response="pushback">Push back</button><button class="outline" data-set-event="${esc(e.id)}" data-response="rest">Prioritise recovery</button></div>`).join('')}
 ${callbacks.length?'<h2 style="font-family:Georgia,serif">Callbacks</h2>':''}${callbacks.map(a=>{const p=projects.get(a.projectId);return `<div class="card"><span class="eyebrow">Ready ${esc(fmtDate(a.readyOn))} · Closes ${esc(fmtDate(a.expiresOn))}</span><h2>${esc(a.title)}</h2><p>${esc(a.character)} · Preparation ${p?preparation(s,p,a.index):0}/60</p><button class="secondary" data-callback="${esc(a.id)}" ${date<a.readyOn?'disabled':''}>Attend callback</button><button class="outline" data-force-callback="${esc(a.id)}">Force win (cheat)</button><button class="outline" data-callback-prepare="${esc(a.id)}">Rehearse for callback</button></div>`}).join('')}
 ${offers.length?'<h2 style="font-family:Georgia,serif">Offers to consider</h2>':''}${offers.map(o=>{
  const p=projects.get(o.projectId);if(!p)return `<div class="card"><h2>${esc(o.title)}</h2><p>Loading this offer’s production…</p></div>`;
  const t=projectSchedule(p),plan=o.source==='contract'?[]:franchisePlan(s,p,o.index,data),conflict=offerConflict(s,catalogue,p,o.contractId),net=Math.round(o.fee*(1-o.agentCommission));
  return `<div class="card"><div class="eyebrow">${o.source==='contract'?'Required franchise return':o.forced?'Guaranteed role offer (cheat)':o.source==='agent'?'Your agent’s approach':'Callback successful'} · Decide before ${esc(fmtDate(o.expiresOn))}</div><h2>${esc(o.title)}</h2><p>As <strong>${esc(o.character)}</strong> · Fee ${money(o.fee)} · After agent commission ${money(net)}</p><p class="muted">Filming ${esc(fmtDate(t.filmingStart))}–${esc(fmtDate(t.filmingEnd))}. Payment at wrap, fame and reception at release.</p>${conflict?'<p class="notice">This shoot conflicts with an existing booking or binding commitment.</p>':''}${o.source==='contract'?'<p class="notice">This return is part of your signed deal. Refusing it—or letting the deadline pass—terminates the contract. You do not need another audition.</p>':''}<button class="primary" data-accept-offer="${esc(o.id)}" ${conflict?'disabled':''}>${o.source==='contract'?'Honour the return':'Accept this role'}</button>${plan.length?`<details><summary>Optional ${plan.length+1}-film deal</summary><p>Accept this film with a 10% higher fee and commit to these mapped returning appearances:</p>${plan.map((e,i)=>`<p>${esc(e.project.title)} · ${e.project.year} · ${esc(e.character)} · Fee ${money(Math.round(o.fee*(1.2+i*.2)))}</p>`).join('')}<p class="muted">These future filming dates become binding. Leaving the deal affects your reputation. Estimated schedules apply.</p><button class="secondary" data-sign-deal="${esc(o.id)}" ${conflict?'disabled':''}>Accept and sign multi-film deal</button></details>`:''}${o.source!=='contract'?`<button class="outline" data-negotiate="${esc(o.id)}" ${o.negotiated?'disabled':''}>${o.negotiated?'Terms negotiated':'Negotiate fee'}</button>`:''}<button class="outline" data-decline-offer="${esc(o.id)}">${o.source==='contract'?'Refuse return and leave franchise':'Decline offer'}</button></div>`
 }).join('')}
 ${contracts.length?'<h2 style="font-family:Georgia,serif">Franchise commitments</h2>':''}${contracts.map(c=>{
  const origin=s.productionOutcomes[c.originProjectId];
  return `<div class="card"><span class="eyebrow">${esc(c.status)}</span><h2>${esc(c.name)}</h2><p>Returning as ${esc(c.character)}.</p>${origin?`<p class="muted">Your earlier film: ${esc(origin.result)} · performance ${origin.performance}/100.</p>`:''}${c.unfairDemands?'<p class="notice">The difficult conditions on this production have made staying in the deal less appealing.</p>':''}${c.entries.map(e=>{const t=projectSchedule(e.project);return `<p><strong>${esc(e.project.title)}</strong> · ${esc(e.status)}<br><span class="muted">Reserved filming ${esc(fmtDate(t.filmingStart))}–${esc(fmtDate(t.filmingEnd))} · ${money(e.fee)}${e.troubled?' · Early script concerns suggest a troubled follow-up.':''}</span></p>`}).join('')}${c.status==='active'?`<label for="leave-${esc(c.id)}">Reason for leaving</label><select id="leave-${esc(c.id)}"><option value="creative concerns">Creative concerns</option><option value="the earlier film’s reception">The earlier film’s reception</option><option value="unfair demands">Unfair demands</option><option value="a different career opportunity">A different career opportunity</option></select><button class="outline" data-leave-contract="${esc(c.id)}">Terminate this contract</button>`:''}</div>`
 }).join('')}`
}

export function bindCareerHub(root,{state:s,catalogue,data,action,save,render,loadCareerYears,toast,modal}){
 root.querySelectorAll('[data-hire-agent]').forEach(b=>b.onclick=()=>action(()=>hireAgent(s,Number(b.dataset.hireAgent))));
 root.querySelectorAll('[data-agent-search]').forEach(b=>b.onclick=()=>action(()=>searchAgentOffers(s,catalogue)));
 root.querySelectorAll('[data-negotiate]').forEach(b=>b.onclick=()=>action(()=>negotiateOffer(s,b.dataset.negotiate)));
 root.querySelectorAll('[data-callback],[data-force-callback]').forEach(b=>b.onclick=()=>{let result;action(()=>{result=attendCallback(s,catalogue,b.dataset.callback||b.dataset.forceCallback,{forceWin:Boolean(b.dataset.forceCallback)})});if(result)modal(`<h2>${result.stage==='offer'?'You have the offer.':'Another actor got the role.'}</h2><p>${result.stage==='offer'?'Review the terms under Offers to consider. Nothing is binding until you accept.':'Keep looking for another opportunity.'}</p>`)});
 root.querySelectorAll('[data-callback-prepare]').forEach(b=>b.onclick=()=>action(()=>{const a=pendingAuditions(s).find(a=>a.id===b.dataset.callbackPrepare),p=[...catalogue,...s.projects].find(p=>p.id===a?.projectId);if(!p)throw Error('This callback is unavailable.');prepareAudition(s,catalogue,p,a.index)}));
 root.querySelectorAll('[data-accept-offer],[data-sign-deal]').forEach(b=>b.onclick=async()=>{try{acceptCareerOffer(s,catalogue,b.dataset.acceptOffer||b.dataset.signDeal,data,{multiFilm:Boolean(b.dataset.signDeal)});save();await loadCareerYears(s);render();toast('Role accepted.')}catch(e){save();render();toast(e.message)}});
 root.querySelectorAll('[data-decline-offer]').forEach(b=>b.onclick=()=>{const offer=pendingOffers(s).find(o=>o.id===b.dataset.declineOffer);if(offer?.contractId&&!confirm('Refusing this required return ends the franchise deal. Continue?'))return;action(()=>declineCareerOffer(s,b.dataset.declineOffer))});
 root.querySelectorAll('[data-leave-contract]').forEach(b=>b.onclick=()=>{if(!confirm('Terminate this binding franchise deal? Your reputation may be affected.'))return;const reason=root.querySelector(`#leave-${b.dataset.leaveContract}`)?.value||'creative concerns';action(()=>terminateContract(s,b.dataset.leaveContract,reason))});
 root.querySelectorAll('[data-set-event]').forEach(b=>b.onclick=()=>action(()=>resolveProductionEvent(s,b.dataset.setEvent,b.dataset.response)))
}
