export const SAVE_KEY='second-take-save-v1';
export const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export const ageAt=(birth,year,month)=>year-Number(birth.slice(0,4))-(month<Number(birth.slice(5,7))?1:0);
export function rand(s){s.rng=(Math.imul(s.rng,1664525)+1013904223)>>>0;return s.rng/4294967296}
export function pick(s,items){return items[Math.floor(rand(s)*items.length)]}
const first=['Avery','Morgan','Jordan','Noah','Elena','Maya','Luca','Theo','Isla','Sofia','Amara','Finn','Cleo','Ezra','Rowan','Riley','Jules','Nina','Leo','Nico','Sam','Aria','Max','Dara'];
const last=['Mercer','Vale','Navarro','Hayes','Okafor','Chen','Reyes','Patel','Arden','Hale','Bennett','Marin','Price','Sato','Brooks','Vega','Bell','Quinn','Rossi','Mills','Stone','Ward','Cruz'];
const adjectives=['Golden','Last','Silent','Broken','Hidden','Midnight','Electric','Distant','Northern','Wild','Blue','Lost','Open','Red','Other'];
const nouns=['Summer','City','Road','Light','Hour','River','Sky','Promise','Kingdom','Heart','Room','Echo','Signal','Shore','Star'];
export function uniqueName(s,kind){const set=kind==='person'?s.usedPeople:s.usedTitles;const base=kind==='person'?`${pick(s,first)} ${pick(s,last)}`:`${pick(s,adjectives)} ${pick(s,nouns)}`;let candidate=base;while(set.includes(candidate))candidate=`${base} ${s.nextId++}`;set.push(candidate);return candidate}
function nextId(s,prefix){return `${prefix}-${s.nextId++}`}
export function person(s,name,occupation='Other',birthYear=s.year-25,relative=''){const p={id:nextId(s,'person'),name,occupation,birthYear,relative,relationship:relative?65:0,chemistry:0,respect:0,rivalry:0,interference:0,alive:true};s.people.push(p);if(!s.usedPeople.includes(name))s.usedPeople.push(name);return p}
export function createCareer({name,birthday,background},catalogue){const birthYear=Number(birthday.slice(0,4));if(!name?.trim()||!/^\d{4}-\d\d-\d\d$/.test(birthday)||birthYear<1956||birthYear>2100||!Number.isFinite(Date.parse(`${birthday}T12:00:00Z`)))throw new Error('Choose a name and a valid birthday from 1956 to 2100.');const year=birthYear+4,month=Number(birthday.slice(5,7));const s={version:1,rng:(birthYear*14137+name.length*113+month)>>>0,nextId:1,year,month,birthday,activeId:'self',people:[],children:[],possessions:[],usedPeople:[],usedTitles:[],projects:[],casts:{},directors:{},filmography:[],relationships:{},timeline:[],notifications:[],choices:[],skills:{acting:8,comedy:5,drama:5},fame:0,respect:0,money:0,health:92,representation:0,background,deathNotices:[],complete:false};person(s,name.trim(),'Aspiring actor',birthYear,'Self').id='self';s.usedPeople.push(...new Set(catalogue.flatMap(p=>p.roles.map(r=>r.actor)).concat(catalogue.map(p=>p.director))));s.usedTitles.push(...catalogue.map(p=>p.title));const familyJob=background==='industry'?pick(s,['Actor','Director','Producer']):pick(s,['Teacher','Nurse','Tradesperson','Office worker']);person(s,uniqueName(s,'person'),familyJob,birthYear-26,'Parent');person(s,uniqueName(s,'person'),pick(s,['Actor','Writer','Teacher','Other']),birthYear-22,'Parent');person(s,uniqueName(s,'person'),pick(s,['Actor','Director','Student','Other']),birthYear+pick(s,[-4,-2,2,4]),'Sibling');if(year>=2026)generatedYear(s,Math.max(2027,year+1));s.timeline.push({year,month,title:'A life begins',body:`${name.trim()} turns four. A future in acting is one possibility, not a requirement.`});return s}
export const active=s=>s.people.find(p=>p.id===s.activeId);
export function ensurePerson(s,name,occupation='Actor',birthYear=null){let p=s.people.find(p=>p.name===name);return p||person(s,name,occupation,birthYear||s.year-30)}
export function generatedYear(s,year){if(year<2027||s.projects.some(p=>p.year===year))return;const directors=s.people.filter(p=>p.occupation==='Director'&&p.alive);for(let i=0;i<3;i++){const director=directors.length&&rand(s)<.3?pick(s,directors).name:uniqueName(s,'person');ensurePerson(s,director,'Director');const title=uniqueName(s,'title');const roles=[];for(let j=0;j<3;j++){const known=s.people.filter(p=>p.occupation==='Actor'&&p.alive&&Math.abs(year-p.birthYear-29)<35);const name=known.length&&rand(s)<.45?pick(s,known).name:uniqueName(s,'person');ensurePerson(s,name,'Actor');roles.push({character:pick(s,['Alex','Charlie','Robin','Taylor','Eden','The Stranger'])+` ${j+1}`,actor:name,ageMin:j===0?16:4,ageMax:j===0?65:85})}s.projects.push({id:nextId(s,'future'),title,year,kind:i===2?'TV series':'Film',director,genre:pick(s,['Drama','Comedy','Action','Thriller','Romance']),roles,generated:true})}}
export function available(s,catalogue){if(s.complete)return[];const a=active(s),age=ageAt(s.birthday,s.year,s.month);if(age<4)return[];const all=[...catalogue,...s.projects];return all.flatMap(p=>p.roles.map((r,i)=>({project:p,role:r,index:i}))).filter(({project:p,role:r,index:i})=>{const target=p.year-s.year;return (target===1&&s.month>=4||target===0&&s.month<=4)&&age>=r.ageMin&&age<=r.ageMax&&!s.casts[`${p.id}:${i}`]&&!s.filmography.some(f=>f.projectId===p.id&&f.personId===a.id)&&!s.choices.includes(`${p.id}:${i}`)}).slice(0,8)}
export function audition(s,project,role,index){const key=`${project.id}:${index}`;if(s.choices.includes(key)||s.casts[key])throw new Error('This part has already been decided.');const a=active(s),age=ageAt(s.birthday,s.year,s.month);if(age<role.ageMin||age>role.ageMax)throw new Error('You are outside this role’s age range.');s.choices.push(key);const directorName=directorFor(s,project);const chance=clamp(.12+s.skills.acting/160+s.fame/300+s.representation*.03+(s.background==='industry'?.06:0)+(s.relationships[directorName]?.respect||0)/400, .08,.88);const win=rand(s)<chance;const original=ensurePerson(s,role.actor,'Actor',role.birthYear);const director=ensurePerson(s,directorName,'Director');if(win){s.casts[key]=a.name;s.filmography.push({projectId:project.id,title:project.title,year:project.year,kind:project.kind,role:role.character,personId:a.id,original:role.actor,director:directorName});s.money+=project.year<1980?1200:project.year<2000?8500:28000;s.fame=clamp(s.fame+pick(s,[3,5,8,10]),0,100);a.fame=s.fame;s.respect=clamp(s.respect+3,0,100);s.relationships[director.name]??={friendship:0,respect:0,chemistry:0};s.relationships[director.name].respect+=8;for(const [i,r] of project.roles.entries()){if(i===index)continue;const costarName=castFor(s,project,i);ensurePerson(s,costarName,'Actor',r.birthYear);const bond=s.relationships[costarName]??={friendship:0,respect:0,chemistry:0};bond.chemistry=clamp(bond.chemistry+5,0,100);bond.respect=clamp(bond.respect+3,0,100)}original.interference++;original.rivalry=clamp(original.rivalry+(original.interference>1?18:5),0,100);if(original.interference>=2)s.timeline.unshift({year:s.year,month:s.month,title:'A rivalry takes shape',body:`You have now won ${original.interference} parts originally associated with ${original.name}. The press begins connecting your careers.`});s.timeline.unshift({year:s.year,month:s.month,title:`Cast in ${project.title}`,body:`You will play ${role.character}. ${original.name} loses this part in your timeline.`});return{win,chance,original:original.name}}s.timeline.unshift({year:s.year,month:s.month,title:`Audition: ${project.title}`,body:`The part of ${role.character} went to ${role.actor}. Your career continues.`});return{win,chance,original:original.name}}
export function train(s,kind){const cost=kind==='acting'&&s.money>500?150:0;if(cost)s.money-=cost;s.skills[kind]=clamp(s.skills[kind]+(cost?3:1),0,100);s.health=clamp(s.health-1,0,100);s.timeline.unshift({year:s.year,month:s.month,title:'Practice',body:`${kind} improves to ${s.skills[kind]}.`})}
export function familyCasting(s,catalogue,year){const family=s.people.filter(p=>p.relative&&p.relative!=='Self'&&p.alive);const projects=[...catalogue,...s.projects].filter(p=>p.year===year);for(const p of projects){const directors=family.filter(f=>f.occupation==='Director'&&year-f.birthYear>=22);if(directors.length&&rand(s)<.09){const f=pick(s,directors);s.directors[p.id]=f.name;s.timeline.unshift({year:s.year,month:s.month,title:'Family behind the camera',body:`${f.name} is directing ${p.title} in this timeline.`})}const actors=family.filter(f=>f.occupation==='Actor');for(let i=0;i<p.roles.length;i++){const r=p.roles[i],eligible=actors.filter(f=>year-f.birthYear>=r.ageMin&&year-f.birthYear<=r.ageMax);if(!eligible.length||s.casts[`${p.id}:${i}`]||rand(s)>=.08)continue;const f=pick(s,eligible);s.casts[`${p.id}:${i}`]=f.name;s.filmography.push({projectId:p.id,title:p.title,year:p.year,kind:p.kind,role:r.character,personId:f.id,original:r.actor,director:s.directors[p.id]||p.director});s.timeline.unshift({year:s.year,month:s.month,title:'A family casting',body:`${f.name} has been cast as ${r.character} in ${p.title}, taking ${r.actor}'s original part.`})}}}
export function advance(s,catalogue){if(s.complete)return;const previous=s.year;s.month++;if(s.month===13){s.month=1;s.year++}const a=active(s);s.health=clamp(s.health+(rand(s)<.55?1:-1),5,100);if(s.year>previous){s.money=Math.round(s.money*0.97);const age=s.year-a.birthYear;if(s.year>=2026)generatedYear(s,Math.max(2027,s.year+1));familyCasting(s,catalogue,s.year+1);const mortality=age<50?.00015:age<75?.002:age<90?.025:.09;if(rand(s)<mortality){die(s,a,rand(s)<.15?'an unexpected illness':'natural causes');return}}if(s.month===Number(s.birthday.slice(5,7))){const age=ageAt(s.birthday,s.year,s.month);if(age>=5&&age<18)s.timeline.unshift({year:s.year,month:s.month,title:`${a.name} turns ${age}`,body:age<13?'Childhood continues. Explore interests or audition.':'Growing independence brings more choices.'})}
 if(rand(s)<.15){const event=pick(s,[{title:'An unexpected invitation',body:'A friend invites you to a small industry gathering.',effect:'social'},{title:'A quiet month',body:'Time to rest, practice, or connect with the people around you.',effect:'rest'},{title:'Under the weather',body:'A passing illness disrupts your plans.',effect:'health'}]);s.notifications.push(event)}if(s.fame>30&&rand(s)<.12)s.notifications.push({title:'Recognised in public',body:'Someone spots you while you are out. Fame is starting to affect ordinary life.',effect:'fame'});if(s.timeline.length>250)s.timeline=s.timeline.slice(0,250);available(s,catalogue)}
export function eventChoice(s,e,choice){if(e.effect==='health')s.health=clamp(s.health-(choice==='engage'?5:2),5,100);else if(e.effect==='rest')s.health=clamp(s.health+5,5,100);else if(e.effect==='social'&&choice==='engage')s.fame=clamp(s.fame+1,0,100);else if(e.effect==='fame'&&choice==='engage')s.fame=clamp(s.fame+1,0,100);s.timeline.unshift({year:s.year,month:s.month,title:e.title,body:`${e.body} You chose to ${choice==='engage'?'engage':'keep to yourself'}.`});s.notifications.shift()}
export function connect(s,name,kind){const a=active(s),p=ensurePerson(s,name);if(p.id===a.id||!p.alive)return false;const pAge=s.year-p.birthYear,aAge=s.year-a.birthYear;if(kind==='date'&&(aAge<18||pAge<18))return false;const r=s.relationships[name]??={friendship:0,respect:0,chemistry:0,dating:false};if(kind==='date'){r.dating=true;r.friendship=clamp(r.friendship+12,-100,100);r.chemistry=clamp(r.chemistry+9,0,100)}else{r.friendship=clamp(r.friendship+6,-100,100);r.chemistry=clamp(r.chemistry+3,0,100)}p.relationship=r.friendship;s.timeline.unshift({year:s.year,month:s.month,title:kind==='date'?`A date with ${name}`:`Time with ${name}`,body:kind==='date'?'A possible romance begins in this fictional timeline.':'You become a little closer.'});return true}
export const shop=[{id:'wardrobe',name:'Premiere wardrobe',price:2000,minAge:16},{id:'car',name:'Car',price:18000,minAge:17},{id:'flat',name:'City apartment',price:120000,minAge:18},{id:'home',name:'Hillside house',price:850000,minAge:18}];
export function buy(s,id){const item=shop.find(x=>x.id===id);if(!item)throw new Error('Unknown purchase.');if(ageAt(s.birthday,s.year,s.month)<item.minAge)throw new Error('You are too young for this purchase.');if(s.money<item.price)throw new Error('You do not have enough money yet.');s.possessions??=[];s.possessions.push({id:item.id,name:item.name,year:s.year,ownerId:s.activeId});s.money-=item.price;if(item.id==='wardrobe')s.fame=clamp(s.fame+1,0,100);s.timeline.unshift({year:s.year,month:s.month,title:'A new purchase',body:`${active(s).name} bought ${item.name.toLowerCase()}.`})}
export function datingApp(s){if(s.year<2012||ageAt(s.birthday,s.year,s.month)<18)throw new Error('Dating apps are unavailable in this era or at this age.');const name=uniqueName(s,'person');const p=person(s,name,'Other',s.year-pick(s,[20,23,27,31,35]));s.timeline.unshift({year:s.year,month:s.month,title:'A new connection',body:`You matched with ${name}. You can get to know them in People.`});return p}
export function haveChild(s,name){const a=active(s);if(ageAt(s.birthday,s.year,s.month)<18)throw new Error('Your character is too young.');name=name.trim();if(!name||s.usedPeople.includes(name))throw new Error('Choose a unique name for the child.');const p=person(s,name,'Child',s.year,'Child');p.birthDate=`${s.year}-${String(s.month).padStart(2,'0')}-01`;s.children.push(p.id);s.timeline.unshift({year:s.year,month:s.month,title:`Welcome, ${name}`,body:`A new generation joins the family. You can switch to them from age four.`});return p}
export function switchTo(s,id){const p=s.people.find(x=>x.id===id);if(!p||!p.alive||ageAt(p.birthDate||`${p.birthYear}-${s.birthday.slice(5)}`,s.year,s.month)<4)throw new Error('This family member cannot be played yet.');const former=active(s);former.fame=s.fame;s.activeId=id;s.birthday=p.birthDate||`${p.birthYear}-${s.birthday.slice(5)}`;s.skills={acting:8,comedy:5,drama:5};s.fame=p.fame??clamp(Math.round(former.fame*.18),0,100);s.timeline.unshift({year:s.year,month:s.month,title:'A new point of view',body:`You now live as ${p.name}. The previous character stays in the world.`})}
export function die(s,p,cause){const wasActive=p.id===s.activeId;if(wasActive)p.fame=s.fame;p.alive=false;const famous=(p.fame||0)>=45;const close=s.children.map(id=>s.people.find(x=>x.id===id)).filter(x=>x?.alive&&s.year-x.birthYear>=4);const headline=famous?`Hollywood mourns ${p.name}`:`Remembering ${p.name}`;const collaborator=s.filmography.find(f=>f.personId===p.id)?.director;const notice={year:s.year,name:p.name,headline,medium:s.year<1985?'Newspaper':s.year<2010?'Television and newspaper':'Social media and news',body:`${p.name} has died at ${s.year-p.birthYear} from ${cause}. ${famous?'Tributes reflect a career that touched audiences across generations.':'Family and friends remember their life.'}`,tributes:collaborator?[`${collaborator} remembers working with ${p.name} on set. (Fictional in-game tribute)`]:[],career:s.filmography.filter(f=>f.personId===p.id).map(f=>f.title)};s.deathNotices.unshift(notice);s.timeline.unshift({year:s.year,month:s.month,title:headline,body:notice.body});if(wasActive){if(close.length)switchTo(s,close[0].id);else s.complete=true}return notice}
export function castFor(s,p,index){return s.casts[`${p.id}:${index}`]||p.roles[index].actor}
export function directorFor(s,p){return s.directors[p.id]||p.director}
