import {active,currentDate,roleFit,projectPhase,projectSchedule,castFor,filmingProjects,train,lifestyle,normaliseGender} from './engine.js?v=15';
import {careerProfile,prepareAudition,preparation,offerConflict,pendingOffers,onSetAction} from './career.js?v=15';
import {featuredOpportunities,applyRole,forceRole,submitAudition,buyAsset,sellAsset,guestEligible,resolveLifeEvent,socialProfile} from './overhaul.js?v=15';
import {ensureOverhaul,roleAssessment,knownFor,castingReason,assets,eraValue,lifestyles,monthlyCosts,openLifeEvent,calendarReason,plusDays} from './game-rules.js?v=15';
let worldQuery='',worldPhase='',worldPage=0,selected=null,rolePage=0;
const currentApps=s=>s.applications.filter(a=>a.personId===s.activeId&&!['rejected','expired','withdrawn','accepted','declined'].includes(a.status));
const find=(s,c,id)=>[...c,...s.projects].find(p=>p.id===id);
function assessment(s,p,index,{esc,money}){const a=roleAssessment(s,p,index);return `<div class="assessment"><span><b>Script ${a.script}/100</b><small>${esc(a.scriptDescription)}</small></span><span><b>Role ${a.quality}/100</b><small>${esc(a.roleDescription)}</small></span></div><p class="muted">${a.billing} · ${a.budgetEstimated?'Simulated':'Reported'} production budget ${money(a.budget)} · Assessments are uncertain (about ±${a.uncertainty}); release results can differ.</p>`}
function applicationCard(s,c,a,u){const {esc,fmtDate}=u,p=find(s,c,a.projectId);if(!p)return '';return `<article class="card application" data-application-card="${esc(a.id)}"><span class="eyebrow">Your application · ${esc(a.status)}</span><h3>${esc(a.title)}</h3><p>${esc(a.character)} · Casting closes ${esc(fmtDate(a.expiresOn))}</p>${['invited','callback'].includes(a.status)?`<p>Preparation ${preparation(s,p,a.index)}/60. ${a.status==='callback'?'The final decision happens automatically when the callback is ready.':'Prepare, then submit; the audition runs automatically.'}</p><button class="outline" data-app-prepare="${esc(a.id)}">Study the script</button><button class="outline" data-app-coach="${esc(a.id)}">Work with a coach</button>${a.status==='invited'?`<button class="primary" data-app-submit="${esc(a.id)}">Submit prepared audition</button>`:''}`:''}${a.status==='offered'?'<button class="primary" data-navigate="career">Review my offer</button>':''}${['watching','considering'].includes(a.status)?'<p class="muted">You will hear from the production when there is a decision. You can continue your life meanwhile.</p>':''}${['invited','considering','callback'].includes(a.status)?`<button class="small" data-app-force="${esc(a.id)}">Force win (cheat)</button>`:''}</article>`}
export function renderToday(root,u){
 const {state:s,catalogue:c,esc,money,fmtDate}=u,actor=active(s),life=ensureOverhaul(s),profile=careerProfile(s),feature=featuredOpportunities(s,c),apps=currentApps(s),shoots=filmingProjects(s,c);
 const age=Number(currentDate(s).slice(0,4))-Number(s.birthday.slice(0,4))-(currentDate(s).slice(5)<s.birthday.slice(5)?1:0);
 const cards=feature.recommendations.map(o=>`<article class="card opportunity" data-opportunity><span class="eyebrow">${esc(o.label)} · ${o.fit}% fit</span><h3>${esc(o.project.title)}</h3><p>As ${esc(o.role.character)} · ${esc(o.project.kind)}</p>${assessment(s,o.project,o.index,u)}<button class="primary" data-apply="${esc(o.project.id)}" data-index="${o.index}">Apply for audition</button><button class="small" data-force-role="${esc(o.project.id)}" data-index="${o.index}">Force win (cheat)</button></article>`);
 if(feature.offer){const o=feature.offer;cards.push(`<article class="card opportunity" data-opportunity><span class="eyebrow">${o.tvCareerId||o.contractId?'Your returning role':o.forced?'Guaranteed offer':'A direct approach'}</span><h3>${esc(o.title)}</h3><p>As ${esc(o.character)} · ${money(o.fee)}</p><p class="muted">Expires ${esc(fmtDate(o.expiresOn))}. Review its schedule, negotiate or choose a multi-film deal in Career.</p><button class="primary" data-navigate="career">Review offer</button></article>`)}
 if(feature.application)cards.push(applicationCard(s,c,feature.application,u).replace('class="card application"','class="card application opportunity" data-opportunity'));
 root.innerHTML=`<section class="hero"><div class="eyebrow">${esc(fmtDate(currentDate(s)))} · Age ${age}</div><h1>${esc(actor.name)}</h1><p>${esc(knownFor(s))}</p><div class="row"><span class="tag">${s.fame>=80?'Global star':s.fame>=50?'Established star':s.fame>=25?'Rising star':'Building a career'}</span><strong>${money(s.money)}</strong></div></section>
 ${s.complete?'<p class="notice">This life has ended. Open Legacy for the retrospective.</p>':''}
 ${normaliseGender(actor.gender)==='unspecified'?'<div class="card"><h2>Choose your casting profile</h2><p>This older save needs a gender to find compatible roles.</p><button data-gender="male">Male</button><button data-gender="female">Female</button><button data-gender="nonbinary">Non-binary</button></div>':''}
 <div class="grid dashboard-stats"><div class="stat"><span>Fame</span><b>${Math.round(s.fame)}/100</b></div><div class="stat"><span>Industry reputation</span><b>${Math.round(profile.reputation)}/100</b></div><div class="stat"><span>Public image</span><b>${Math.round(life.publicImage)}/100</b></div><div class="stat"><span>Acting / health</span><b>${s.skills.acting} / ${s.health}</b></div></div>
 <section><div class="row"><h2>Your next opportunities</h2><span class="pill">${cards.length} highlighted</span></div><p class="muted">Two strong fits, a possible breakthrough, a direct offer once established, and one application needing attention. Every other eligible role is searchable in World.</p><div class="opportunity-grid">${cards.join('')||'<div class="card"><p>No fitting auditions are casting today. Browse announced productions in World or move forward in time.</p></div>'}</div><button class="secondary" data-navigate="world">Explore all productions</button></section>
 <details class="card"><summary>My applications (${apps.length})</summary>${apps.map(a=>applicationCard(s,c,a,u)).join('')||'<p>No active applications.</p>'}</details>
 ${shoots.map(p=>`<article class="card"><span class="eyebrow">Currently filming</span><h2>${esc(p.title)}</h2><p>Until ${esc(fmtDate(projectSchedule(p).filmingEnd))}. Ordinary filming happens automatically.</p><button class="outline" data-onset="rehearse" data-project="${esc(p.id)}">Rehearse scenes</button><button class="outline" data-onset="teamwork" data-project="${esc(p.id)}">Support the cast</button><button class="outline" data-onset="rest" data-project="${esc(p.id)}">Rest between takes</button><button class="secondary" data-navigate="people">Castmates & relationships</button></article>`).join('')}
 <div class="card"><h2>Make time</h2><p>${Math.round(s.energy)} energy. Small conversations fit around filming. Ceremonies, interviews and holidays must fit your calendar.</p><div class="grid"><button class="secondary" data-train="acting">Practice acting</button><button class="secondary" data-train="drama">Practice drama</button><button class="secondary" data-train="comedy">Practice comedy</button><button class="secondary" data-rest>Rest & recover</button><button class="secondary" data-fitness>Exercise</button></div><button class="primary" data-advance="1">Next week →</button><button class="secondary" data-advance="4">Advance four weeks</button>${s.advanceRemaining?`<button class="outline" data-resume>Resume remaining ${s.advanceRemaining} days</button>`:''}</div>
 <details class="card"><summary>Calendar (${s.productionCalendar.length+s.commitments.filter(x=>x.personId===s.activeId&&x.status==='scheduled').length})</summary>${[...s.productionCalendar,...s.commitments.filter(x=>x.personId===s.activeId&&x.status==='scheduled')].sort((a,b)=>a.start.localeCompare(b.start)).map(x=>`<p><strong>${esc(x.title)}</strong><br>${esc(fmtDate(x.start))}–${esc(fmtDate(x.end))}</p>`).join('')||'<p>Your calendar is open.</p>'}</details>
 <details class="card"><summary>Life, money & luxuries</summary><p>Income received ${money(life.income)} · Living costs paid or owed ${money(life.expenses)} · Debt ${money(life.debt)}</p><label for="livingStandard">Living arrangement</label><select id="livingStandard">${Object.entries(lifestyles).map(([k,v])=>`<option value="${k}" ${life.lifestyle===k?'selected':''} ${age<18&&k!=='family'?'disabled':''}>${esc(v.name)} · ${money(v.monthly*eraValue(s.year))}/month</option>`).join('')}</select><p>Combined upkeep: ${money(monthlyCosts(s))}/month.</p><div class="asset-grid">${assets.filter(a=>age>=a.minAge&&s.year>=(a.minYear||1960)).map(a=>{const owned=s.possessions.some(p=>p.id===a.id&&p.ownerId===s.activeId);return `<div><h3>${esc(a.name)}</h3><p>${money(a.price*eraValue(s.year))} · ${money(a.monthly*eraValue(s.year))}/month upkeep</p><button class="outline" ${owned?`data-sell="${a.id}"`:`data-buy-asset="${a.id}" ${s.money<a.price*eraValue(s.year)?'disabled':''}`}>${owned?'Sell asset':'Buy'}</button></div>`}).join('')}</div></details>
 <section><h2>Recent history</h2>${s.timeline.slice(0,3).map(t=>`<article class="card"><time class="eyebrow">${esc(t.date||t.year)}</time><h3>${esc(t.title)}</h3><p>${esc(t.body)}</p></article>`).join('')}</section>`;
 bind(root,u);
 root.querySelectorAll('[data-gender]').forEach(b=>b.onclick=()=>u.action(()=>actor.gender=b.dataset.gender));
 root.querySelectorAll('[data-onset]').forEach(b=>b.onclick=()=>u.action(()=>onSetAction(s,c,b.dataset.project,b.dataset.onset)));
 root.querySelectorAll('[data-train]').forEach(b=>b.onclick=()=>u.action(()=>train(s,b.dataset.train)));
 root.querySelector('[data-rest]').onclick=async()=>{u.action(()=>lifestyle(s,'rest'));await u.advanceWeeks(1)};
 root.querySelector('[data-fitness]').onclick=()=>u.action(()=>lifestyle(s,'fitness'));
 root.querySelectorAll('[data-advance]').forEach(b=>b.onclick=()=>u.advanceWeeks(Number(b.dataset.advance)));
 root.querySelector('[data-resume]')?.addEventListener('click',()=>u.advanceWeeks(0,{resume:true}));
 root.querySelector('#livingStandard').onchange=e=>u.action(()=>{life.lifestyle=e.target.value});
 root.querySelectorAll('[data-buy-asset]').forEach(b=>b.onclick=()=>u.action(()=>buyAsset(s,b.dataset.buyAsset)));
 root.querySelectorAll('[data-sell]').forEach(b=>b.onclick=()=>u.action(()=>sellAsset(s,b.dataset.sell)));
}
function reasonFor(s,c,p,index){const fit=roleFit(s,p,p.roles[index]),phase=projectPhase(s,p),key=`${p.id}:${index}`;return castingReason(s,p,index)||(fit<=50?'Applications require more than 50% fit.':'')||(s.casts[key]||s.choices.includes(key)?'This role has been decided.':'')||(s.filmography.some(f=>f.projectId===p.id&&f.personId===s.activeId&&f.status!=='withdrawn')?'You already have a role in this production.':'')||(offerConflict(s,c,p)?'Filming conflicts with an accepted commitment.':'')||(!['Announced','Casting'].includes(phase)?'This production is no longer taking applications.':'')}
export function renderWorld(root,u){
 const {state:s,catalogue:c,esc,fmtDate}=u,q=worldQuery.toLowerCase(),all=[...new Map([...c,...s.projects].map(p=>[p.id,p])).values()],filtered=all.filter(p=>(!worldPhase||projectPhase(s,p)===worldPhase)&&(!q||[p.title,p.director,p.genre,...p.roles.flatMap(r=>[r.actor,r.character])].some(v=>String(v||'').toLowerCase().includes(q)))).sort((a,b)=>Math.abs(a.year-s.year)-Math.abs(b.year-s.year)||a.title.localeCompare(b.title)),pages=Math.max(1,Math.ceil(filtered.length/16));worldPage=Math.min(worldPage,pages-1);
 const focused=all.find(p=>p.id===selected),roleMatches=focused?focused.roles.map((r,i)=>({r,i})).filter(({r})=>!q||focused.title.toLowerCase().includes(q)||[r.actor,r.character].some(v=>String(v||'').toLowerCase().includes(q))):[];
 root.innerHTML=`<section class="hero"><div class="eyebrow">Discover & pursue</div><h1>The production world</h1><p>Apply for every individual open role above 50% fit, or register interest in an announced production. Returning characters belong to their established performers.</p></section><div class="card"><label for="worldSearch">Search productions, actors or characters</label><input id="worldSearch" value="${esc(worldQuery)}" placeholder="Stranger Things, Jenna Ortega, Mike…"><div class="grid"><div><label for="worldPhase">Production stage</label><select id="worldPhase">${['','Announced','Casting','Filming','Post-production','Released'].map(v=>`<option value="${v}" ${worldPhase===v?'selected':''}>${v||'All stages'}</option>`).join('')}</select></div><div><label for="browseYear">Load another historical year</label><select id="browseYear"><option value="">Choose a year</option>${Array.from({length:67},(_,i)=>1960+i).map(y=>`<option>${y}</option>`).join('')}</select></div></div><p class="muted">${filtered.length.toLocaleString()} matching productions in loaded years. Page ${worldPage+1} of ${pages}. Filming dates are estimated when not documented.</p></div>
 ${focused?`<article class="card role-browser"><button class="small" data-close-production>← Close production</button><h2>${esc(focused.title)}</h2><p>${esc(projectPhase(s,focused))} · ${focused.year} · ${esc(focused.genre)}<br>Filming ${esc(fmtDate(projectSchedule(focused).filmingStart))}–${esc(fmtDate(projectSchedule(focused).filmingEnd))} · Release ${esc(fmtDate(projectSchedule(focused).releaseDate))}</p><p class="muted">${roleMatches.length} credited roles. Some credits are brief appearances, not large playable parts.</p>${roleMatches.slice(rolePage*20,(rolePage+1)*20).map(({r,i})=>{const reason=reasonFor(s,c,focused,i),a=s.applications.find(a=>a.personId===s.activeId&&a.projectId===focused.id&&a.index===i&&!['expired','rejected','withdrawn','declined'].includes(a.status));return `<section class="world-role" data-world-role="${i}"><div class="row"><h3>${esc(r.character)}</h3><span class="pill">${roleFit(s,focused,r)}% fit</span></div><p>Played by ${esc(castFor(s,focused,i))}${r.episodeCount?` · ${r.episodeCount} credited episodes`:''}</p>${assessment(s,focused,i,u)}${a?`<p class="notice">Your application: ${esc(a.status)}.</p>`:`<button class="primary" data-apply="${esc(focused.id)}" data-index="${i}" ${reason?'disabled':''}>${projectPhase(s,focused)==='Announced'?'Register interest':'Apply for audition'}</button>${!reason&&projectPhase(s,focused)==='Casting'?`<button class="small" data-force-role="${esc(focused.id)}" data-index="${i}">Force win (cheat)</button>`:''}`}${reason?`<p class="action-reason">${esc(reason)}</p>`:''}</section>`}).join('')||'<p>No roles match this search; clear the search to view the whole cast.</p>'}<div class="grid"><button id="rolesPrev" ${rolePage===0?'disabled':''}>Previous roles</button><button id="rolesNext" ${(rolePage+1)*20>=roleMatches.length?'disabled':''}>Next roles</button></div></article>`:''}
 <div class="production-grid">${filtered.slice(worldPage*16,(worldPage+1)*16).map(p=>`<article class="card"><span class="eyebrow">${esc(projectPhase(s,p))} · ${p.year} · ${esc(p.kind)}</span><h2>${esc(p.title)}</h2><p>${esc(p.genre)} · ${esc(p.director)}</p><p>${p.roles.length.toLocaleString()} credits</p><button class="secondary" data-open-production="${esc(p.id)}">Browse individual roles</button></article>`).join('')||'<article class="card">No productions match. Load another year or change the filter.</article>'}</div><div class="grid"><button id="worldPrev" ${worldPage===0?'disabled':''}>← Previous</button><button id="worldNext" ${worldPage+1>=pages?'disabled':''}>Next →</button></div>`;
 bind(root,u);
 root.querySelector('#worldSearch').oninput=e=>{const pos=e.target.selectionStart;worldQuery=e.target.value;worldPage=rolePage=0;renderWorld(root,u);const input=root.querySelector('#worldSearch');input.focus();input.setSelectionRange(pos,pos)};
 root.querySelector('#worldPhase').onchange=e=>{worldPhase=e.target.value;worldPage=0;renderWorld(root,u)};
 root.querySelector('#browseYear').onchange=async e=>{const year=Number(e.target.value);if(year)try{e.target.disabled=true;await u.loadYear(year);u.render()}catch(err){u.toast(err.message)}};
 root.querySelectorAll('[data-open-production]').forEach(b=>b.onclick=()=>{selected=b.dataset.openProduction;rolePage=0;renderWorld(root,u);root.querySelector('.role-browser').scrollIntoView({block:'start'})});
 root.querySelector('[data-close-production]')?.addEventListener('click',()=>{selected=null;renderWorld(root,u)});
 for(const [id,step] of [['worldPrev',-1],['worldNext',1],['rolesPrev',-1],['rolesNext',1]])root.querySelector('#'+id)?.addEventListener('click',()=>{if(id.startsWith('roles'))rolePage+=step;else worldPage+=step;renderWorld(root,u)});
}
function bind(root,u){const {state:s,catalogue:c}=u;
 root.querySelectorAll('[data-navigate]').forEach(b=>b.onclick=()=>u.navigate(b.dataset.navigate));
 root.querySelectorAll('[data-apply]').forEach(b=>b.onclick=()=>u.action(()=>{const p=find(s,c,b.dataset.apply);applyRole(s,c,p,Number(b.dataset.index),{watch:projectPhase(s,p)==='Announced'});u.toast('Application saved. Updates will arrive as time passes.')}));
 root.querySelectorAll('[data-force-role]').forEach(b=>b.onclick=()=>u.action(()=>{forceRole(s,c,find(s,c,b.dataset.forceRole),Number(b.dataset.index));u.navigate('career')}));
 root.querySelectorAll('[data-app-prepare],[data-app-coach]').forEach(b=>b.onclick=()=>u.action(()=>{const a=s.applications.find(a=>a.id===(b.dataset.appPrepare||b.dataset.appCoach));prepareAudition(s,c,find(s,c,a.projectId),a.index,b.dataset.appCoach?'coach':'script')}));
 root.querySelectorAll('[data-app-submit]').forEach(b=>b.onclick=()=>u.action(()=>submitAudition(s,c,b.dataset.appSubmit)));
 root.querySelectorAll('[data-app-force]').forEach(b=>b.onclick=()=>u.action(()=>{const a=s.applications.find(a=>a.id===b.dataset.appForce);if(a.status==='callback'){const callback=s.careerAuditions.find(x=>x.id===a.callbackId);if(callback)callback.status='withdrawn';a.status='invited'}submitAudition(s,c,a.id,{forceWin:true});u.navigate('career')}));
}
export function awardsMarkup(s,{esc,fmtDate}){const awards=s.awards.filter(a=>a.personId===s.activeId);return `<details class="card"><summary>Awards & nominations (${awards.length})</summary>${awards.map(a=>`<article class="award-record"><span class="eyebrow">${a.year} · ${esc(a.status==='nominated-final'?'Nominee':a.status)}</span><h3>${esc(a.name)}</h3><p>${esc(a.title)} · ${esc(a.category)}<br>${a.productionAward?'Production recognition; not a personal acting win.':'Personal acting recognition.'} Ceremony ${esc(fmtDate(a.ceremonyDate))}</p></article>`).join('')||'<p>Released performances can earn major, television or independent recognition. Small films can open doors through reputation and awards.</p>'}</details>`}
export function presentEvent(u){
 const {state:s,catalogue:c,esc,fmtDate}=u,e=openLifeEvent(s),existing=document.querySelector('.life-event-modal');if(!e){existing?.remove();return}if(existing?.dataset.eventId===e.id)return;existing?.remove();
 const modal=document.createElement('div');modal.className='modal life-event-modal';modal.dataset.eventId=e.id;modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-labelledby','lifeEventTitle');
 const guest=e.type==='award-invitation',guests=guest?s.people.filter(p=>guestEligible(s,p,e.data.ceremonyDate)):[];
 const when=e.data.ceremonyDate||e.data.appearanceDate,clash=when?calendarReason(s,when,plusDays(when,1)):'';
 modal.innerHTML=`<div><span class="eyebrow">${esc(e.type.replaceAll('-',' '))} · ${esc(fmtDate(e.date))}</span><h2 id="lifeEventTitle">${esc(e.title)}</h2><p class="event-copy">${esc(e.body)}</p>${guest?`<label for="awardGuest">Choose a guest</label><select id="awardGuest"><option value="">Select someone</option>${guests.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}${s.relationships[p.name]?.dating?' · partner':p.relative?' · family':' · friend'}</option>`).join('')}</select><p class="muted">A partner, friend or relative can come. They may decline. Attendance does not change who wins.</p>`:''}${clash?`<p class="notice">${esc(clash)}</p>`:''}<div class="event-options">${e.options.map(o=>`<button class="${o.id==='ack'||o.id==='attend'?'primary':'secondary'}" data-life-answer="${o.id}" ${clash&&['attend','alone','guest'].includes(o.id)?'disabled':''}>${esc(o.label)}</button>`).join('')}</div><p class="muted">Time pauses until you answer.${s.advanceRemaining?` ${s.advanceRemaining} days remain from your requested advance.`:''}</p><p class="notice" id="eventError" hidden></p></div>`;
 document.body.append(modal);modal.querySelectorAll('[data-life-answer]').forEach(b=>b.onclick=()=>{try{resolveLifeEvent(s,c,e.id,b.dataset.lifeAnswer,{guestId:modal.querySelector('#awardGuest')?.value||null});u.save();modal.remove();u.render()}catch(err){const error=modal.querySelector('#eventError');error.hidden=false;error.textContent=err.message}});modal.querySelector('button')?.focus();
}
