const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const {gunzipSync}=require('node:zlib');
(async()=>{
 const browser=await chromium.launch({headless:true});const context=await browser.newContext({serviceWorkers:'block'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const requests=[];page.on('request',r=>{if(r.url().includes('/data/years/'))requests.push(r.url())});
 await page.goto('http://127.0.0.1:8765');await page.locator('#name').fill('Adult Performance Test');await page.locator('#birthday').fill('1996-02-17');await page.locator('#startAdult').click();assert.equal(await page.locator('#startDate').inputValue(),'2014-02-17');await page.locator('#startDate').fill('2020-01-15');const began=Date.now();await page.locator('#new button[type=submit]').click();await page.locator('#auditionSearch').waitFor({timeout:120000});console.log('Real 2020 start loaded in',Date.now()-began,'ms');assert.ok(await page.locator('[data-audition]').count()>0);assert.ok(requests.some(u=>u.includes('2022.json.gz')));assert.ok(!requests.some(u=>u.includes('2000.json.gz')));
 const getSave=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('second-take-save-v1')));
 assert.equal((await getSave()).date,'2020-01-15');assert.equal((await getSave()).birthday,'1996-02-17');
 await page.locator('#auditionSearch').fill('zz-no-such-film');assert.equal(await page.locator('[data-audition]').count(),0);await page.locator('#auditionSearch').fill('');
 await page.locator('[data-shortlist]').first().click();await page.locator('[data-close]').click();await page.locator('[data-force-audition]').first().click();await page.locator('[data-close]').click();await page.locator('[data-accept-offer]').first().click();
 await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('second-take-save-v1'));s.people.push({id:'test-adult',name:'Test Castmate',occupation:'Actor',birthYear:1990,relative:'',alive:true},{id:'test-minor',name:'Young Castmate',occupation:'Actor',birthYear:2010,relative:'',alive:true});s.relationships['Test Castmate']={friendship:10,respect:12,chemistry:14,dating:false};s.relationships['Young Castmate']={friendship:3,respect:4,chemistry:0,dating:false};localStorage.setItem('second-take-save-v1',JSON.stringify(s))});await page.reload();await page.locator('#auditionSearch').waitFor();await page.locator('#settingsButton').click();await page.locator('#openCheats').click();await page.locator('[data-cheat="acting"]').click();assert.equal((await getSave()).skills.acting,100);assert.equal((await getSave()).skills.drama,5);await page.locator('[data-cheat="drama"]').click();await page.locator('#cheatPerson').selectOption('test-adult');await page.locator('[data-cheat="friendship"]').click();assert.equal((await getSave()).relationships['Test Castmate'].chemistry,14);await page.locator('[data-cheat="respect"]').click();await page.locator('[data-cheat="chemistry"]').click();{const r=(await getSave()).relationships['Test Castmate'];assert.equal(r.friendship,100);assert.equal(r.respect,100);assert.equal(r.chemistry,100);assert.equal(r.dating,false)}await page.locator('#cheatPerson').selectOption('test-minor');await page.locator('[data-cheat="chemistry"]').click();assert.equal((await getSave()).relationships['Young Castmate'].chemistry,0);await page.locator('[data-close]').click();
 await page.locator('summary').filter({hasText:'Choose representation'}).click();await page.locator('[data-hire-agent=\"1\"]').click();
 const timings=[];
 for(let i=0;i<105;i++){
  const before=(await getSave()).date,t=Date.now();await page.locator('[data-advance="4"]').click();await page.waitForFunction(d=>JSON.parse(localStorage.getItem('second-take-save-v1')).date!==d,before);timings.push(Date.now()-t);
  if((await getSave()).complete)throw Error('Unexpected early completion');
 }
 const s=await getSave();assert.ok(s.year>=2028);assert.ok(s.filmography.filter(f=>f.personId!==s.activeId).length<=8*6);assert.ok(JSON.stringify(s).length<2000000);console.log(JSON.stringify({endDate:s.date,familyCredits:s.filmography.filter(f=>f.personId!==s.activeId).length,saveBytes:JSON.stringify(s).length,medianFourWeeksMs:timings.sort((a,b)=>a-b)[Math.floor(timings.length/2)],maxFourWeeksMs:Math.max(...timings)}));assert.ok(Math.max(...timings)<5000,'Four-week progression stays responsive');
 await page.locator('[data-tab="world"]').click();await page.locator('#worldSearch').fill('zzz');await page.locator('#worldSearch').fill('');await page.locator('[data-tab="people"]').click();await page.reload();await page.locator('#auditionSearch').waitFor();assert.equal((await getSave()).skills.acting,100);assert.equal((await getSave()).skills.drama,100);
 // An old save with an excluded production still completes its shoot and gets paid.
 const full=JSON.parse(gunzipSync(fs.readFileSync('data/archive/years/2024.json.gz'))),selected=new Set(JSON.parse(gunzipSync(fs.readFileSync('data/years/2024.json.gz'))).projects.map(p=>p.id));const old=full.projects.find(p=>!selected.has(p.id)&&p.kind==='Film'&&p.roles.length);
 await page.evaluate(async p=>{const engine=await import('./engine.js?v=14');const r=p.roles[0],birthYear=p.year-(r.characterAge??Math.round((r.ageMin+r.ageMax)/2)),t=engine.projectSchedule(p);const s=engine.createCareer({name:'Legacy Save Test',birthday:`${Math.max(1900,Math.min(2000,birthYear))}-01-01`,startDate:t.castingStart,gender:r.gender},[]);s.filmography.push({projectId:p.id,title:p.title,year:p.year,kind:p.kind,role:r.character,personId:s.activeId,status:'booked',fee:28000},{projectId:'old-family',title:'Old family credit',year:1970,personId:s.people[1].id});s.usedPeople.push(...Array.from({length:20000},(_,i)=>`Unused ${i}`));localStorage.setItem('second-take-save-v1',JSON.stringify(s))},old);
 const prior=requests.length;await page.reload();await page.locator('#auditionSearch').waitFor({timeout:120000});await page.locator('[data-advance="1"]').click();assert.ok(!(await getSave()).usedPeople.some(n=>n.startsWith('Unused ')));assert.ok(!requests.slice(prior).some(u=>u.includes('1970.json.gz')));const migrated=await getSave();assert.equal(migrated.filmography[0].title,old.title);
 // Jump near wrap through the saved state and reload to verify the archived booking remains active.
 await page.evaluate(async()=>{const engine=await import('./engine.js?v=14');const s=JSON.parse(localStorage.getItem('second-take-save-v1'));const response=await fetch('./data/archive/years/2024.json.gz');const data=await (await import('./catalogue.js?v=14')).readCatalogueResponse(response,true);const p=data.projects.find(p=>p.id===s.filmography[0].projectId),t=engine.projectSchedule(p);s.date=new Date(Date.parse(t.filmingEnd+'T12:00:00Z')-7*86400000).toISOString().slice(0,10);s.year=Number(s.date.slice(0,4));s.month=Number(s.date.slice(5,7));s.filmography[0].status='filming';localStorage.setItem('second-take-save-v1',JSON.stringify(s))});await page.reload();await page.locator('#auditionSearch').waitFor({timeout:120000});await page.locator('[data-advance="1"]').click();assert.equal((await getSave()).filmography[0].status,'post-production');assert.equal((await getSave()).money,28000);
 assert.deepEqual(errors,[]);console.log('Browser checks passed: custom adult start, separate cheats, eight-year playthrough, saved reload, and legacy booking recovery.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
