const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),{gunzipSync}=require('node:zlib');
(async()=>{
 const browser=await chromium.launch(),page=await browser.newPage({serviceWorkers:'block'}),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/data/years/'))requests.push(r.url())});
 const get=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('second-take-save-v1')));
 const clearEvents=async()=>{for(let i=0;i<30&&await page.locator('.life-event-modal').count();i++){const m=page.locator('.life-event-modal');let clicked=false;for(const id of ['ack','decline','pass','ignore','honest','reduce','rest']){const b=m.locator(`[data-life-answer="${id}"]:not([disabled])`);if(await b.count()){await b.click();clicked=true;break}}if(!clicked)await m.locator('button:not([disabled])').first().click()}};
 await page.goto('http://127.0.0.1:8765');await page.locator('#name').fill('Adult Performance Test');await page.locator('#birthday').fill('1996-02-17');await page.locator('#startAdult').click();assert.equal(await page.locator('#startDate').inputValue(),'2014-02-17');await page.locator('#startDate').fill('2020-01-15');const began=Date.now();await page.locator('#new button[type=submit]').click();await page.locator('[data-advance="1"]').waitFor({timeout:120000});console.log('Real 2020 start loaded in',Date.now()-began,'ms');assert.ok(await page.locator('[data-opportunity]').count()<=5);assert.ok(await page.locator('[data-force-role]').count()>0);assert.ok(requests.some(u=>u.includes('2022.json.gz')));assert.ok(!requests.some(u=>u.includes('2000.json.gz')));
 assert.equal((await get()).birthday,'1996-02-17');await page.locator('[data-force-role]').first().click();await page.locator('[data-accept-offer]').first().click();assert.equal((await get()).filmography.filter(f=>f.personId==='self').length,1);assert.equal((await get()).money,0);
 await page.locator('#settingsButton').click();await page.locator('#openCheats').click();await page.locator('[data-cheat="acting"]').click();assert.equal((await get()).skills.acting,100);assert.equal((await get()).skills.drama,5);await page.locator('[data-cheat="drama"]').click();await page.locator('[data-close]').click();await page.locator('[data-tab="home"]').click();
 const timings=[];
 for(let i=0;i<105;i++){
  const before=(await get()).date,t=Date.now();await page.locator('[data-advance="4"]').click();await page.waitForFunction(d=>JSON.parse(localStorage.getItem('second-take-save-v1')).date!==d,before);await clearEvents();
  for(let j=0;j<20&&(await get()).advanceRemaining;j++){await page.locator('[data-resume]').click();await clearEvents()}
  assert.equal((await get()).advanceRemaining,0);timings.push(Date.now()-t);assert.ok(await page.locator('[data-opportunity]').count()<=5);if((await get()).complete)throw Error('Unexpected early completion');
 }
 const s=await get(),bytes=JSON.stringify(s).length;assert.ok(s.year>=2028);assert.ok(s.filmography.filter(f=>f.personId!==s.activeId).length<=8*6);assert.ok(bytes<2000000);const sorted=[...timings].sort((a,b)=>a-b);console.log(JSON.stringify({endDate:s.date,familyCredits:s.filmography.filter(f=>f.personId!==s.activeId).length,saveBytes:bytes,medianFourWeeksMs:sorted[Math.floor(sorted.length/2)],maxFourWeeksMs:Math.max(...timings)}));assert.ok(sorted[Math.floor(sorted.length/2)]<3000);assert.ok(Math.max(...timings)<15000);
 await page.locator('[data-tab="world"]').click();await page.locator('#worldSearch').fill('zzz');await page.locator('#worldSearch').fill('');await page.reload();await page.locator('[data-advance="1"]').waitFor();assert.equal((await get()).skills.acting,100);assert.equal((await get()).skills.drama,100);
 const full=JSON.parse(gunzipSync(fs.readFileSync('data/archive/years/2024.json.gz'))),selected=new Set(JSON.parse(gunzipSync(fs.readFileSync('data/years/2024.json.gz'))).projects.map(p=>p.id));const old=full.projects.find(p=>!selected.has(p.id)&&p.kind==='Film'&&p.roles.length);
 await page.evaluate(async p=>{const e=await import('./engine.js?v=15'),r=p.roles[0],birthYear=p.year-(r.characterAge??Math.round((r.ageMin+r.ageMax)/2)),t=e.projectSchedule(p),s=e.createCareer({name:'Legacy Save Test',birthday:`${Math.max(1900,Math.min(2000,birthYear))}-01-01`,startDate:t.castingStart,gender:r.gender},[]);s.filmography.push({projectId:p.id,title:p.title,year:p.year,kind:p.kind,role:r.character,personId:s.activeId,status:'booked',fee:28000},{projectId:'old-family',title:'Old family credit',year:1970,personId:s.people[1].id});s.usedPeople.push(...Array.from({length:20000},(_,i)=>`Unused ${i}`));localStorage.setItem(e.SAVE_KEY,JSON.stringify(s))},old);
 const prior=requests.length;await page.reload();await page.locator('[data-advance="1"]').waitFor({timeout:120000});assert.ok(!(await get()).usedPeople.some(n=>n.startsWith('Unused ')));assert.ok(!requests.slice(prior).some(u=>u.includes('1970.json.gz')));assert.equal((await get()).filmography[0].title,old.title);
 await page.evaluate(async()=>{const e=await import('./engine.js?v=15'),s=JSON.parse(localStorage.getItem(e.SAVE_KEY)),data=await(await import('./catalogue.js?v=15')).readCatalogueResponse(await fetch('./data/archive/years/2024.json.gz'),true),p=data.projects.find(p=>p.id===s.filmography[0].projectId),t=e.projectSchedule(p);s.date=new Date(Date.parse(t.filmingEnd+'T12:00:00Z')-7*86400000).toISOString().slice(0,10);s.year=+s.date.slice(0,4);s.month=+s.date.slice(5,7);s.filmography[0].status='filming';s.lifeEvents=[];localStorage.setItem(e.SAVE_KEY,JSON.stringify(s))});await page.reload();await page.locator('[data-advance="1"]').waitFor({timeout:120000});await page.locator('[data-advance="1"]').click();await clearEvents();assert.equal((await get()).filmography[0].status,'post-production');assert.equal((await get()).money,28000);
 assert.deepEqual(errors,[]);console.log('Curated browser passed: custom adult start, bounded shortlist, guaranteed offer, eight-year playthrough with event resume, saved reload and legacy booking payments.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
