const {chromium}=require('playwright'),{gzipSync,gunzipSync}=require('node:zlib'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true}),page=await browser.newPage({serviceWorkers:'block'}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const film=year=>({id:`fixture-${year}`,title:`Fixture Film ${year}`,year,kind:'Film',genre:'Drama',director:'Fixture Director',collectionId:'fixture',castingStartDate:`${year-1}-01-01`,filmingStartDate:`${year-1}-08-01`,filmingEndDate:`${year-1}-10-01`,releaseDate:`${year}-06-01`,roles:[{actor:'Original Actor',character:'Alex Vale',gender:'male',birthYear:1980,characterAge:year-1980,ageMin:year-1980-5,ageMax:year-1980+9},{actor:'Co-star',character:'Casey Reed',gender:'female',birthYear:1980,ageMin:18,ageMax:40}]});
 const parts=[2001,2003,2005].map(film),data={collections:{fixture:{id:'fixture',name:'Fixture Collection',parts}},projectCollections:Object.fromEntries(parts.map(p=>[p.id,'fixture']))};
 await page.route('**/data/years/index.json*',r=>r.fulfill({json:{years:Array.from({length:67},(_,i)=>1960+i),compression:'gzip',totals:{projects:67,roles:134}}}));
 await page.route('**/data/years/*.json.gz',r=>{const year=Number(r.request().url().match(/(\d{4})\.json/)[1]);return r.fulfill({body:gzipSync(JSON.stringify({year,projects:[film(year)]}))})});
 await page.route('**/data/franchises.json.gz*',r=>r.fulfill({body:gzipSync(JSON.stringify(data))}));
 await page.route('**/data/tv-seasons/index.json.gz*',r=>r.fulfill({body:gzipSync(JSON.stringify({shows:{},years:[]}))}));
 const save=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('second-take-save-v1')));
 const restore=async s=>{await page.evaluate(s=>localStorage.setItem('second-take-save-v1',JSON.stringify(s)),s);await page.reload();await page.locator('#auditionSearch').waitFor()};
 const jump=async date=>{const s=await save();s.date=date;s.year=Number(date.slice(0,4));s.month=Number(date.slice(5,7));await restore(s)};
 const next=async()=>{const d=(await save()).date;await page.locator('[data-advance="1"]').click();await page.waitForFunction(d=>JSON.parse(localStorage.getItem('second-take-save-v1')).date!==d,d)};
 await page.goto('http://127.0.0.1:8765');await page.locator('#name').fill('Contract Browser Test');await page.locator('#birthday').fill('1980-01-01');await page.locator('#startDate').fill('2000-01-01');await page.locator('#new button.primary').click();await page.locator('#auditionSearch').waitFor();
 await page.locator('#auditionSearch').fill('Alex Vale');await page.locator('[data-prepare][data-kind="script"]').first().click();assert.equal(Object.values((await save()).preparations)[0].score,15);await page.locator('[data-force-audition]').first().click();await page.locator('[data-close]').click();assert.equal((await save()).filmography.length,0);
 await page.locator('summary').filter({hasText:'Optional 3-film deal'}).click();await page.locator('[data-sign-deal]').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('second-take-save-v1')).contracts.length===1);
 const signed=await save();assert.equal(signed.contracts[0].entries.length,2);assert.equal(signed.filmography.length,1);
 await jump('2000-07-25');await next();await page.locator('[data-set-action="teamwork"]').click();assert.equal((await save()).filmography[0].performance.teamwork,5);
 const filming=await save();filming.productionEvents=filming.productionEvents.filter(e=>e.status!=='open');filming.productionEvents.push({id:'fixture-event',projectId:'fixture-2001',personId:filming.activeId,status:'open',createdOn:filming.date,title:'Fixture pressure',body:'Fictional unfair demands.'});await restore(filming);await page.locator('[data-set-event="fixture-event"][data-response="pushback"]').click();assert.equal((await save()).contracts[0].unfairDemands,true);
 await jump('2001-12-25');await next();await page.locator('[data-accept-offer]').click();assert.equal((await save()).filmography.filter(f=>f.personId==='self').length,2);
 await jump('2003-12-25');await next();await page.locator('[data-accept-offer]').click();assert.equal((await save()).filmography.filter(f=>f.personId==='self').length,3);
 await jump('2005-06-15');await next();assert.equal((await save()).contracts[0].status,'completed');
 await restore(signed);await jump('2001-12-25');await next();const rep=(await save()).careerProfiles.self.reputation;await page.locator('[data-decline-offer]').click();assert.equal((await save()).contracts[0].status,'terminated');assert.ok((await save()).careerProfiles.self.reputation<rep);
 console.log('Browser contract fixture passed: non-binding offer, signed reservations, mandatory returns, completion and refusal.');
 const real=await browser.newPage({serviceWorkers:'block'});real.on('pageerror',e=>errors.push(e.message));
 const catalogue=JSON.parse(gunzipSync(fs.readFileSync('data/years/2003.json.gz'))),pirates=catalogue.projects.find(p=>p.title.includes('Pirates of the Caribbean')),index=pirates.roles.findIndex(r=>r.character==='Jack Sparrow');assert.ok(index>=0);
 await real.goto('http://127.0.0.1:8765');const date=await real.evaluate(async p=>(await import('./engine.js?v=11')).projectSchedule(p).castingStart,pirates);
 await real.locator('#name').fill('Real Franchise Test');await real.locator('#birthday').fill(`${pirates.roles[index].birthYear}-01-01`);await real.locator('#startDate').fill(date);await real.locator('#new button.primary').click();await real.locator('#auditionSearch').waitFor({timeout:120000});await real.locator('#auditionSearch').fill('Jack Sparrow');
 await real.locator(`[data-force-audition="${pirates.id}"][data-index="${index}"]`).click();await real.locator('[data-close]').click();await real.locator('summary').filter({hasText:'Optional 3-film deal'}).click();await real.locator('[data-sign-deal]').click();await real.waitForFunction(()=>JSON.parse(localStorage.getItem('second-take-save-v1')).contracts.length===1);
 const contract=await real.evaluate(()=>JSON.parse(localStorage.getItem('second-take-save-v1')).contracts[0]);assert.ok(contract.name.includes('Pirates'));assert.ok(contract.entries.every(e=>e.character==='Jack Sparrow'));console.log('Real franchise deal passed:',contract.entries.map(e=>e.project.title));
 assert.deepEqual(errors,[]);await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
