const {chromium}=require('playwright');const {gzipSync}=require('node:zlib');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({serviceWorkers:'block'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/data/years/index.json*',r=>r.fulfill({json:{years:Array.from({length:67},(_,i)=>1960+i),compression:'gzip',totals:{projects:3685,roles:3685}}}));
await page.route('**/data/years/*.json.gz',r=>{const year=Number(r.request().url().match(/(\d{4})\.json/)[1]);const projects=Array.from({length:55},(_,i)=>({id:`tmdb-${year}-${i}`,title:`Production ${String(i).padStart(2,'0')}`,year,castingYear:year-1,castingStartDate:`${year-1}-01-01`,filmingStartDate:`${year-1}-08-01`,filmingEndDate:`${year-1}-10-01`,releaseDate:`${year}-06-01`,kind:i%2?'Film':'TV series',director:'Test Director',roles:[{character:`Character ${i}`,actor:`Actor ${i}`,gender:'male',birthYear:year-5,characterAge:5,ageMin:4,ageMax:17}]}));return r.fulfill({contentType:'application/octet-stream',body:gzipSync(JSON.stringify({year,projects}))})});
await page.goto('http://127.0.0.1:8765');await page.locator('#name').fill('Browser Test');await page.locator('#birthday').fill('1996-01-01');await page.locator('#new button.primary').click();await page.locator('#auditionSearch').waitFor();assert.equal(await page.locator('[data-audition]').count(),20);await page.locator('#auditionNext').click();assert.equal(await page.locator('[data-audition]').count(),20);await page.locator('#auditionNext').click();assert.equal(await page.locator('[data-audition]').count(),15);await page.locator('#auditionSearch').fill('Character 54');assert.equal(await page.locator('[data-audition]').count(),1);await page.locator('[data-shortlist]').click();await page.locator('.modal').waitFor();await page.locator('[data-close]').click();await page.locator('[data-force-audition]').click();await page.locator('.modal').waitFor();assert.ok((await page.locator('.modal').innerText()).includes('You have the offer.'));assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('second-take-save-v1')).filmography.filter(f=>f.personId==='self'&&f.status==='booked').length),0);await page.locator('[data-close]').click();await page.locator('[data-accept-offer]').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('second-take-save-v1')).filmography.filter(f=>f.personId==='self'&&f.status==='booked').length),1);await page.locator('#auditionSearch').fill('');const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('second-take-save-v1')).date);await page.locator('[data-advance="1"]').click();await page.waitForFunction(d=>JSON.parse(localStorage.getItem('second-take-save-v1')).date!==d,before);
assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('second-take-save-v1')).date),'2000-01-08');await page.locator('[data-life="rest"]').click();

await page.reload();await page.locator('#auditionSearch').waitFor();assert.equal(errors.length,0,errors.join('\n'));console.log('Browser fixture passed: full audition pages, search, shortlist, audition, next week, rest and reload.');
const real=await browser.newPage({serviceWorkers:'block'});real.on('pageerror',e=>errors.push(e.message));
await real.goto('http://127.0.0.1:8765');await real.locator('#name').fill('Real Catalogue Test');await real.locator('#birthday').fill('1956-01-01');await real.locator('#new button.primary').click();await real.locator('#auditionSearch').waitFor({timeout:120000});assert.ok(await real.locator('[data-audition]').count()>0);await real.locator('#settingsButton').click();assert.ok((await real.locator('.modal').innerText()).includes('Version 1.2'));await real.locator('[data-close]').click();await real.locator('[data-tab="world"]').click();await real.locator('#worldSearch').waitFor();await real.reload();await real.locator('#auditionSearch').waitFor({timeout:120000});assert.equal(errors.length,0,errors.join('\n'));console.log('Real catalogue browser test passed: first playable year, auditions, World and saved-game reload.');await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
