const {chromium}=require('playwright'),assert=require('node:assert/strict'),{gzipSync}=require('node:zlib');
const project=(id,extra={})=>({id,title:id,year:2020,kind:'Film',director:'Director',genre:'Drama',releaseDate:'2020-06-01',filmingStartDate:'2020-03-01',filmingEndDate:'2020-05-01',castingStartDate:'2020-01-01',voteCount:5000,popularity:30,baselineRating:8,roles:[{character:'Alex',actor:'Original Actor',birthYear:1996,gender:'male',ageMin:18,ageMax:30,characterAge:24}],...extra});
(async()=>{
 const browser=await chromium.launch(),page=await browser.newPage({serviceWorkers:'block',viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const projects=Array.from({length:15},(_,i)=>project('Film '+i));projects.push(project('Returning Show Season 2',{kind:'TV series',seriesId:'show',seriesTitle:'Returning Show',seasonNumber:2}));projects.push(project('Announced Film',{castingStartDate:'2020-02-01'}));
 await page.route('**/data/filmographies/index.json*',r=>r.fulfill({json:{years:[],shows:{}}}));
 await page.route('**/data/years/index.json*',r=>r.fulfill({json:{years:[2019,2020,2021,2022],compression:'gzip'}}));
 await page.route('**/data/years/*.json.gz',r=>r.fulfill({body:gzipSync(JSON.stringify({year:Number(r.request().url().match(/(\d{4})\.json/)[1]),projects:r.request().url().includes('2020.json')?projects:[]}))}));
 await page.route('**/data/tv-seasons/index.json.gz*',r=>r.fulfill({body:gzipSync(JSON.stringify({shows:{},years:[]}))}));
 await page.route('**/data/casting-history/years/*.json.gz',r=>r.fulfill({body:gzipSync(JSON.stringify({projects:{'Returning Show Season 2':{0:{firstYear:2019}}}}))}));
 await page.goto('http://127.0.0.1:8765');await page.locator('#name').fill('Overhaul Test');await page.locator('#birthday').fill('1996-01-01');await page.locator('#startAdult').click();assert.equal(await page.locator('#startDate').inputValue(),'2014-01-01');await page.locator('#startDate').fill('2020-01-01');await page.locator('#new button[type=submit]').click();await page.locator('[data-advance="1"]').waitFor();
 const get=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('second-take-save-v1')));
 assert.equal((await get()).overhaulVersion,5);assert.ok(await page.locator('[data-opportunity]').count()<=5);assert.equal(await page.locator('[data-apply]').count(),3);
 await page.locator('[data-apply]').first().click();assert.equal((await get()).applications.length,1);assert.ok(await page.locator('[data-opportunity]').count()<=5);
 await page.locator('[data-tab="world"]').click();await page.locator('#worldSearch').fill('Returning Show');await page.locator('[data-open-production]').click();assert.ok((await page.locator('.world-role').innerText()).includes('Established character'));assert.equal(await page.locator('.world-role [data-apply]').isDisabled(),true);
 await page.locator('#worldSearch').fill('Announced Film');await page.locator('[data-open-production]').click();await page.locator('.world-role [data-apply]').click();assert.ok((await get()).applications.some(a=>a.status==='watching'));
 await page.locator('#worldSearch').fill('Film 1');await page.locator('[data-open-production]').first().click();await page.locator('[data-force-role]').first().click();await page.locator('[data-accept-offer]').first().waitFor();await page.locator('[data-negotiate]').first().click();await page.locator('[data-accept-offer]').first().click();assert.equal((await get()).filmography.filter(f=>f.personId==='self').length,1);assert.equal((await get()).money,0);
 // Event pauses exactly on release, preserves remaining time, and resumes after acknowledgement.
 await page.evaluate(async()=>{const e=await import('./engine.js?v=15'),s=JSON.parse(localStorage.getItem(e.SAVE_KEY));s.date='2020-05-30';s.year=2020;s.month=5;s.filmography[0].status='post-production';s.filmography[0].paidNet=s.filmography[0].fee;s.skills={acting:100,drama:100,comedy:100};s.money=100000;for(const a of s.applications)if(a.status!=='accepted')a.status='expired';localStorage.setItem(e.SAVE_KEY,JSON.stringify(s))});await page.reload();await page.locator('[data-advance="4"]').click();await page.locator('.life-event-modal').waitFor();assert.equal((await get()).date,'2020-06-01');assert.equal((await get()).advanceRemaining,26);assert.ok((await get()).fame>0);
 const clearEvents=async()=>{for(let i=0;i<20&&await page.locator('.life-event-modal').count();i++){const box=page.locator('.life-event-modal');if(await box.locator('[data-life-answer="decline"]').count())await box.locator('[data-life-answer="decline"]').click();else if(await box.locator('[data-life-answer="ack"]').count())await box.locator('[data-life-answer="ack"]').click();else await box.locator('button:not([disabled])').first().click()}};
 await clearEvents();await page.locator('[data-resume]').click();await clearEvents();if((await get()).advanceRemaining)await page.locator('[data-resume]').click();await clearEvents();assert.ok((await get()).date>='2020-06-01');
 // Save-reload, independent cheats, deeper profiles and adult gates.
 await page.evaluate(async()=>{const e=await import('./engine.js?v=15'),s=JSON.parse(localStorage.getItem(e.SAVE_KEY));e.person(s,'Avery Vale','Teacher',1995,'','female');s.relationships['Avery Vale']={friendship:80,respect:20,chemistry:80,dating:false};s.money=100000;s.lifeEvents=[];s.fame=20;localStorage.setItem(e.SAVE_KEY,JSON.stringify(s))});await page.reload();await page.locator('[data-tab="people"]').click();await page.locator('[data-profile]').filter({hasText:'Avery Vale'}).click();assert.equal(await page.locator('progress').count(),6);for(let i=0;i<6;i++)await page.locator('[data-social="friend"]').click();assert.ok((await get()).relationships['Avery Vale'].friendship>80);await page.locator('[data-deep-social="future"]').click();assert.ok((await get()).relationships['Avery Vale'].trust>0);
 const before=(await get()).date;await page.locator('[data-social="walk"]').click();assert.equal((await get()).date,before);await page.locator('#circleBack').click();await page.locator('[data-meet="community"]').click();assert.equal((await get()).date,before);await page.locator('.person-hero').waitFor();
 await page.locator('#settingsButton').click();assert.match(await page.locator('.modal').innerText(),/Version 1.5/);await page.locator('#openCheats').click();await page.locator('[data-cheat="acting"]').click();assert.equal((await get()).skills.acting,100);await page.locator('#allowRecasting').check();assert.equal((await get()).allowRecasting,true);await page.locator('[data-close]').click();
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);await page.locator('[data-tab="home"]').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);assert.ok(await page.locator('[data-opportunity]').count()<=5);await page.screenshot({path:'/tmp/second-take-v15-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log('v1.5 browser passed: shortlist, role lock, announced interest, forced offers, negotiation, acceptance, exact-date event pause/resume, cash preservation, profiles, independent cheats and mobile layout.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
